//! Shared script execution helpers.
//!
//! Lifecycle hooks (`docs/specs/core/install/scripts/SPEC.md`) and `rpm run`
//! (`docs/specs/cli/run/SPEC.md`) share one script-execution contract: each
//! script string runs through the platform shell and the project
//! `node_modules/.bin` is prepended to `PATH`. This module owns the two pieces
//! both execution paths reuse so there is a single shell invocation model,
//! not two.

use std::{env, ffi::OsString, fs, path::Path, process::Command};

/// Build the platform shell command that executes `script` through
/// `/bin/sh -c` on Unix and `cmd /C` on Windows, so command chaining,
/// quoting, and environment assignment follow normal package-script
/// semantics. The caller sets the working directory and `PATH`.
#[cfg(unix)]
pub(crate) fn shell_command(script: &str) -> Command {
    let mut command = Command::new("/bin/sh");
    command.arg("-c").arg(script);
    command
}

#[cfg(windows)]
pub(crate) fn shell_command(script: &str) -> Command {
    let mut command = Command::new("cmd");
    command.arg("/C").arg(script);
    command
}

/// Prepend `<bin_root>/node_modules/.bin` to the inherited `PATH` and return
/// the joined value. `bin_root` is the project root whose `node_modules/.bin`
/// the script should see: the project root for root hooks and `rpm run`, or
/// the staged `node_modules` root for resolved-package hooks whose `.bin` was
/// generated by the preceding `link` phase.
pub(crate) fn script_path(bin_root: &Path) -> Result<OsString, std::io::Error> {
    let mut paths = vec![fs::canonicalize(bin_root)?
        .join("node_modules")
        .join(".bin")];
    if let Some(path) = env::var_os("PATH") {
        paths.extend(env::split_paths(&path));
    }

    env::join_paths(paths)
        .map_err(|error| std::io::Error::new(std::io::ErrorKind::InvalidInput, error))
}

/// Prepend `<modules_dir>/.bin` to the inherited `PATH` and return the joined
/// value. Use this when the caller already holds the `node_modules` directory
/// itself (for example the staged `node_modules` during the lifecycle `scripts`
/// phase), so the `.bin` directory produced by the preceding `link` phase is
/// reachable without re-joining a redundant `node_modules` segment.
pub(crate) fn script_path_for_modules_dir(modules_dir: &Path) -> Result<OsString, std::io::Error> {
    let mut paths = vec![fs::canonicalize(modules_dir)?.join(".bin")];
    if let Some(path) = env::var_os("PATH") {
        paths.extend(env::split_paths(&path));
    }

    env::join_paths(paths)
        .map_err(|error| std::io::Error::new(std::io::ErrorKind::InvalidInput, error))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::{
        fs,
        os::unix::fs::PermissionsExt,
        path::PathBuf,
        sync::atomic::{AtomicU64, Ordering},
        time::{SystemTime, UNIX_EPOCH},
    };

    static TEMP_PROJECT_ID: AtomicU64 = AtomicU64::new(0);

    struct TempProject {
        root: PathBuf,
    }

    impl TempProject {
        fn new() -> Self {
            let nanos = SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .map(|duration| duration.as_nanos())
                .unwrap_or(0);
            let counter = TEMP_PROJECT_ID.fetch_add(1, Ordering::SeqCst);
            let root =
                env::temp_dir().join(format!("rpm-script-runner-{}-{nanos}", std::process::id()));
            let root = root.with_extension(counter.to_string());
            fs::create_dir_all(&root).unwrap();
            Self { root }
        }
    }

    impl Drop for TempProject {
        fn drop(&mut self) {
            let _ = fs::remove_dir_all(&self.root);
        }
    }

    #[test]
    fn script_path_includes_node_modules_bin() {
        let temp = TempProject::new();
        let bin = temp
            .root
            .join("node_modules")
            .join(".bin")
            .join("fixture-bin");
        fs::create_dir_all(bin.parent().unwrap()).unwrap();
        fs::write(&bin, "#!/bin/sh\necho bin-ok > bin.txt\n").unwrap();
        let mut permissions = fs::metadata(&bin).unwrap().permissions();
        permissions.set_mode(0o755);
        fs::set_permissions(&bin, permissions).unwrap();

        let mut command = shell_command("fixture-bin");
        command.current_dir(&temp.root);
        command.env("PATH", script_path(&temp.root).unwrap());
        let status = command.status().unwrap();

        assert_eq!(status.code().unwrap(), 0);
        assert_eq!(
            fs::read_to_string(temp.root.join("bin.txt")).unwrap(),
            "bin-ok\n"
        );
    }

    #[test]
    fn shell_command_runs_through_sh_on_unix() {
        let temp = TempProject::new();
        let mut command = shell_command("echo chained > out.txt && echo two >> out.txt");
        command.current_dir(&temp.root);
        command.env("PATH", script_path(&temp.root).unwrap());
        let status = command.status().unwrap();

        assert_eq!(status.code().unwrap(), 0);
        assert_eq!(
            fs::read_to_string(temp.root.join("out.txt")).unwrap(),
            "chained\ntwo\n"
        );
    }
}
