name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  verify:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Check formatting
      run: cargo fmt --check
    - name: Check compilation
      run: cargo check
    - name: Lint
      run: cargo clippy --all-targets --all-features
    - name: Run tests
      run: cargo test
