name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  verify:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Check formatting
      run: cargo fmt --check
    - name: Check compilation
      run: cargo check
    - name: Lint
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Run tests
      run: cargo test
    - name: Install llvm tools
      run: rustup component add llvm-tools-preview
    - name: Install coverage tool
      uses: taiki-e/install-action@cargo-llvm-cov
    - name: Check coverage
      run: rustup run stable cargo llvm-cov --locked --lib --bins --all-features --fail-under-lines 90
